### ISSUE TITLE
Contact Us form – after submitting info, the modal is in an odd state.

### ISSUE THREAD

**Issue by kenhowardpdx** [csgpro/csgpro.com#100]
> Contact Us form – after submitting info, the modal is in an odd state.

Reported in #93

**Comment by kenhowardpdx** [comment]
@Listbd Can you provide a screenshot of what you were experiencing?

**Comment by Listbd** [comment]
![image](https://cloud.githubusercontent.com/assets/7220137/16530304/5dd67904-3f7c-11e6-9533-e62e343a6ce1.png)

I'm thinking that everything below "We'll be in touch" could be hidden. Or, maybe reset the fields so they are _all_ blank and not yellow.

**Comment by kenhowardpdx** [comment]
@Listbd Thank you. 😃

**Comment by kenhowardpdx** [comment]
@Listbd @JamieMikami Please review. Deployed to https://csgnext.azurewebsites.net

**Comment by Listbd** [comment]
Looks good! :sheep:
