### ISSUE TITLE
Rogue Gray X in mobile.

### ISSUE THREAD

**Issue by kenhowardpdx** [csgpro/csgpro.com#107]
> In mobile view, on my phone (Galaxy S5), I see a gray X in the upper right hand corner on the same level and the collapsed menu icon, that, when pressed, disappears, leaving a square outline behind.

**Comment by kenhowardpdx** [comment]
@tedbcsgpro Would you mind confirming this issue is resolved?

**Comment by tedbcsgpro** [comment]
Looks good. No more X in the upper right corner!

**Comment by kenhowardpdx** [comment]
@JamieMikami Please review. Deployed to https://csgnext.azurewebsites.net
