### ISSUE TITLE
site text updates

### ISSUE THREAD

**Issue by JamieMikami** [csgpro/csgpro.com#110]
Need to update the site with new text, and with an additional image.

https://basecamp.com/2844982/projects/11501341/uploads/32638156#events_upload_32638156

new text is for the  About, Custom Solutions, Analytics and the reach out popup.

image is to be placed on the about and the custom soutions page.  it could also go on the home page if there is room or we replace something.

**Comment by kenhowardpdx** [comment]
@JamieMikami these changes have been deployed. Please review.

**Comment by JamieMikami** [comment]
These look good, thanks.  the logo is a bit big on the Custom Solutions page, but you have it nearly at the limit with the small subhead text.  I don't think I would change it for now.  I will send a link out to the team for a final review then we can push to production.

**Comment by kenhowardpdx** [comment]
I can resize "Microsoft Partner" to reduce the footprint. I don't know how MS would feel about it though.

**Comment by JamieMikami** [comment]
Just leave for now
