### ISSUE TITLE
unable to mark a customer story active in database

### ISSUE THREAD

**Issue by JamieMikami** [csgpro/csgpro.com#111]
setting isactive to false did not remove images from the bottom set of stories.  Also, it would be nice to be able to have stories in the top not also appear at the bottom.  

isactive should remove an image from the bottom set of stories and inslider should control (which it does) the stories in the top slider.

**Comment by kenhowardpdx** [comment]
@JamieMikami Please review

**Comment by JamieMikami** [comment]
Now if it is marked isactive = false it is gone from both the bottom and the slider.  The slider should ignore the isactive flag and just use the inslider.  While I agree that isactive could easily mean remove it completely, it doesn't allow for the finite control to only remove from one area.

**Comment by kenhowardpdx** [comment]
Ah. Ok. I misunderstood the request.

**Comment by kenhowardpdx** [comment]
@JamieMikami Once CI is complete (https://travis-ci.org/csgpro/csgpro.com) this will be ready for review. I've updated the DB so the featured (inSlider) stories don't appear in the bottom section (isActive).

**Comment by kenhowardpdx** [comment]
@JamieMikami  Travis is done. You can review now: https://csgnext.azurewebsites.net/stories
