### ISSUE TITLE
Main content is positioned right on medium breakpoint

### ISSUE THREAD

**Issue by kenhowardpdx** [csgpro/csgpro.com#113]
From @tedbcsgpro:
> The only minor thing I noticed is a browser sizing behavior between 640px-1024px, there is a left margin as the main content div is still floated right with a width of 75%.  I would recommend a media query for this range to set the width to be 100% or remove the float.  Or, muck with the show-for-medium class to force the left column to render. 

![image003](https://cloud.githubusercontent.com/assets/1892667/16695832/c71493c2-44f6-11e6-8a92-42be2be74722.jpg)

**Comment by kenhowardpdx** [comment]
@tedbcsgpro @JamieMikami plz rvw (view it https://csgnext.azurewebsites.net/business-analytics)

**Comment by tedbcsgpro** [comment]
works great on chrome and IE :shipit:
