### ISSUE TITLE
Update About Page

### ISSUE THREAD

**Issue by JamieMikami** [csgpro/csgpro.com#157]
Change text on the page and add an image below the App/Dev gold image.

Eventually link the image to a blog post Chuck makes on the MCSE certification.

**Comment by JamieMikami** [comment]
New About page text:
CSG Pro builds modern software solutions that expand knowledge through a more informed and visual use of data.  Through Business Analytics and Custom Software Solutions, CSG Pro delivers value by helping clients intelligently collect, analyze and visualize data to make informed decisions and streamline their business processes. We integrate cloud and mobile to allow for scale, enhance the user-experience and ensure long-term payoff.

CSG Pro is a Microsoft Gold Partner in Application Development.   CSG Pro's consultants are dedicated to learning and sharing new technologies, processes and solutions as evidenced by Charter Member Status as Microsoft Certified Solution Experts in Data Management and Analytics, along with the leadership and active participation of Microsoft Power BI and Microsoft Typescript User Groups.   

Headquartered in Portland Oregon's urban, tech-savvy Pearl District, CSG Pro is committed to delighting its clients through the innovative application of modern technology solutions. We hope to have the opportunity to build something amazing for you today, as we have for so many since 1993.

**Comment by JamieMikami** [comment]
![mcse_charter](https://cloud.githubusercontent.com/assets/16297562/19424688/153e5b5e-93e0-11e6-818e-0e5fbd912f61.png)

**Comment by JamieMikami** [comment]
This image above is to be placed directly below the gold partner logo.

**Comment by kenhowardpdx** [comment]
I'll look at this tomorrow and push to prod https://github.com/csgpro/csgpro.com/commit/39185c3281104547346c09aa989d8cce91eee34b

**Comment by JamieMikami** [comment]
Ok, I sent you some slacks on it, not a rush.  but it did push my commit to master instead of my created branch.
